# Site settings
title: DYOS
email: your-email@domain.com
description: "Graag laat ik u zien waar mijn werk uit bestaat. Ik heb me gespecialiseerd in het vermaken van ‘oude’ sieraden. Het goud of zilver en de edelstenen vormen de basis voor het nieuwe ontwerp wat geheel in samenspraak met de klant gemaakt wordt."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://atelier-dyos.nl" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
